### ISSUE TITLE
Support new nushell version

### ISSUE THREAD

**Issue by dzorya** [FMotalleb/nu_plugin_audio_hook#3]
plugin fails to register with new Nushell version:
![image](https://github.com/user-attachments/assets/6a629cf4-c590-477d-95a8-5508e2be4cdd)

**Comment by fmotalleb** [comment]
How did you updated the plugin?
I've tested latest stable version on nu 0.97.1 windows, debian and arch linux and its was ok.

**Comment by dzorya** [comment]
dz-artix:~> cargo install nu_plugin_audio_hook --features=all-decoders
    Updating crates.io index
  Installing nu_plugin_audio_hook v0.1.12
    Updating crates.io index
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.12
   Compiling cfg-if v1.0.0
....
Finished release [optimized] target(s) in 2m 08s
  Installing /home/denis/.local/share/cargo/bin/nu_plugin_audio_hook
   Installed package `nu_plugin_audio_hook v0.1.12` (executable `nu_plugin_audio_hook`)

dz-artix:~> plugin add /home/denis/.local/share/cargo/bin/nu_plugin_audio_hook
Error: nu::shell::plugin_failed_to_decode

  × Plugin failed to decode: unknown variant `Error`, expected one of `Hello`, `Option`, `CallResponse`, `EngineCall`, `Data`, `End`,
  │ `Drop`, `Ack`

dz-artix:~>

**Comment by fmotalleb** [comment]
ah so thats why
the cargo package is not updated yet, Ill update it now but you can use 
```bash
cargo install nu_plugin_audio_hook --features=all-decoders --git=https://github.com/FMotalleb/nu_plugin_audio_hook
```
to install it for now

**Comment by dzorya** [comment]
It worked.
You might want to change register in description to plugin add:
![image](https://github.com/user-attachments/assets/73d63a09-cffe-40ca-b995-99a9916900fe)

**Comment by fmotalleb** [comment]
Package is updated on cargo
and readme is fixed
Thank you for reporting the issue
